config/routes.rb
Rails.application.routes.draw do
  root "flights#index"
  resources :flights
  resources :bookings, only: [:new, :create, :show]
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, class_name: 'Flight', foreign_key: 'departure_airport_id'
  has_many :arriving_flights, class_name: 'Flight', foreign_key: 'arrival_airport_id'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers
  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :departure_airport, class_name: 'Airport'
  belongs_to :arrival_airport, class_name: 'Airport'
  has_many :bookings
  has_many :passengers, through: :bookings
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking
  has_many :flights, through: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @flight = Flight.find(params[:flight_id])
    @booking = Booking.new

    params[:passengers].to_i.times { @booking.passengers.build }
  end

  def create
    @booking = Booking.new(booking_params)
    if @booking.save
      redirect_to @booking
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @booking = Booking.find(params[:id])
    @flight = Flight.find(@booking.flight_id)
    @passengers = @booking.passengers
  end

  private 

  def booking_params
    params.require(:booking).permit(:flight_id, passengers_attributes: [:name, :email])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @flights = Flight.where(departure_airport_id: params[:departure_airport_id])
                      .and(Flight.where(arrival_airport_id: params[:arrival_airport_id]))
                      .select { |flight| flight.start.to_date.strftime('%d/%m/%Y') == params[:start] }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<h1>Passenger information</h1>
<%= form_with model: @booking do |form| %>
  <ul>
    <%= form.fields_for :passengers do |f| %>
      <li>
        <%= f.label :name %>
        <%= f.text_field :name %> 
        <%= f.label :email %>
        <%= f.email_field :email %>
      </li>
    <% end %>
  </ul>
  <%= form.hidden_field :flight_id, value: @flight.id %>
  <%= form.submit %>
<% end %>

app/views/bookings/show.html.erb
<h1>Flight detail</h1>
<ul>
  <li>Flight number: <%= @flight.id %></li>
  <li>Flight date: <%= @flight.start.strftime('%d %b %Y - %H:%M %Z') %></li>
  <li>Departure airport: <%= @flight.departure_airport.airport %></li>
  <li>Arrival airport: <%= @flight.arrival_airport.airport %></li>
</ul>

<h1>Passengers</h2>
<ul>
  <% @passengers.each do |passenger| %>
    <li>
      <p>Name: <%= passenger.name %></p>
      <p>Email: <%= passenger.email %></p>
    </li>
  <% end %>
</ul>

app/views/flights/_search_form.html.erb
<%= form_with method: :get do |form| %>
  <%= form.label :departure_airport_id, 'Departure airport:' %><br>
  <%= form.collection_select :departure_airport_id, Airport.order(:airport), :id, :airport, { selected: params[:departure_airport_id], include_blank: true } , { required: true } %><br><br>
  <%= form.label :arrival_airport_id, 'Arrival airport:' %><br>
  <%= form.collection_select :arrival_airport_id, Airport.order(:airport), :id, :airport, { selected: params[:arrival_airport_id], include_blank: true }, { required: true } %><br><br>
  <%= form.label :passengers, 'Number of passengers:' %><br>
  <%= form.select :passengers, [1, 2, 3, 4], { selected: params[:passengers], include_blank: true }, { required: true } %><br><br>
  <%= form.label :start, 'Flight date:' %><br>
  <%= form.select :start, Flight.order(:start).pluck(:start).map {|date| date.to_date.strftime('%d/%m/%Y')}.uniq, { selected: params[:start], include_blank: true }, { required: true } %><br><br>
  <%= form.submit 'Search' %>
<% end %>

app/views/flights/index.html.erb
<%= render 'search_form' %>
<% if params[:departure_airport_id] != nil %>
  <% if @flights.empty? %>
    <p>There are no available flights</p>
  <% else %>
    <%= form_with url: new_booking_path, method: :get do |form| %>
      <%= form.hidden_field :passengers, value: params[:passengers] %>
      <ul>
        <% @flights.each do |flight| %>
          <li>
            <%= form.radio_button :flight_id, flight.id %>
            <%= "#{flight.departure_airport.airport} to #{flight.arrival_airport.airport}, #{flight.start.strftime('%Y-%m-%d %H:%M')}" %>
          </li>
        <% end %>
        <%= form.submit 'Choose flight' %>
      </ul>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>